language: node_js

node_js:
  - "12"

install:
  - npm install
cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE testing_companies;' -U postgres

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls

addons:
  postgresql: "9.6"
